//Types
export const GET_AVAILABLE_CASES_COUNT = '[AGENT] GET_AVAILABLE_CASES_COUNT';
export const OPEN_CASE = '[AGENT] OPEN_CASE';
export const GET_ACTIVE_CASE = '[AGENT] GET_ACTIVE_CASE';
export const GET_CASE_HISTORIES = '[AGENT] GET_CASE_HISTORIES';
export const UPDATE_WEBSITE_STATUS = '[AGENT] UPDATE_WEBSITE_STATUS';
export const AGENT_SEND_FEEDBACK = '[AGENT] AGENT_SEND_FEEDBACK';
export const AGENT_RESOLVE_CASE = '[AGENT] AGENT_RESOLVE_CASE';
//Status
export const PROGRESS = '_PROGRESS';
export const PENDING = '_PENDING';
export const SUCCESS = '_SUCCESS';
export const FAILED = '_FAILED';