//Types
export const USER_VERIFICATION = '[ADMIN: USER_MANAGEMENT] USER_VERIFICATION';
export const GET_USER_LIST = '[ADMIN: USER_MANAGEMENT] GET_USER_LIST';
export const CREATE_PLAN = '[ADMIN: PRICING PLAN] CREATE_PLAN';
export const DELETE_PLAN = '[ADMIN: PRICING PLAN] DELETE_PLAN';
export const UPDATE_PLAN = '[ADMIN: PRICING PLAN] UPDATE_PLAN';
export const SET_SELECTED_PLAN = '[ADMIN: PRICING PLAN] SET_SELECTED_PLAN';
export const PRICING_PLAN_RESET_MSG = '[ADMIN: PRICING PLAN] PRICING_PLAN_RESET_MSG';

//Status
export const PROGRESS = '_PROGRESS';
export const PENDING = '_PENDING';
export const SUCCESS = '_SUCCESS';
export const FAILED = '_FAILED';
